CXX = g++
CXXFLAGS = -std=c++11

SRCS =C:\cygwin64\home\ozeem\myLibraryProject\myCodeFile.cpp
OBJS = $(SRCS:.cpp=.o)
EXEC = library_management_system

True: $(EXEC)

$(EXEC): $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) -o $(EXEC)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(EXEC)
